import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {Drawer} from "@/components/Drawer";
import React from "react";
import {UserProvider} from "@/context/UserContext";
import {OrganisationProvider} from "@/context/OrganisationContext";
import {TaskProvider} from "@/context/TaskContext";

const roboto = Roboto({subsets: ["latin"], weight: ["400", "500", "700", "900"] });

export const metadata: Metadata = {
  title: "marraph",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {

    return (
        <html lang="en">
            <body className={roboto.className}>
                <UserProvider id={1}>
                    <OrganisationProvider id={1}>
                        <TaskProvider>
                            <div className={"flex flex-row"}>
                                <Drawer></Drawer>
                                <div className={"w-full flex flex-col space-y-4 p-8"}>
                                    {children}
                                </div>
                            </div>
                        </TaskProvider>
                    </OrganisationProvider>
                </UserProvider>
            </body>
        </html>
    );
}
